package com.goodluck2u.gl2u.dao;

import com.goodluck2u.gl2u.entity.UserStockTradeLog;
import com.goodluck2u.gl2u.entity.UserStockTradeLogExample;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
@Mapper
public interface UserStockTradeLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_stock_trade_log
     *
     * @mbg.generated Wed Mar 04 20:59:48 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_stock_trade_log
     *
     * @mbg.generated Wed Mar 04 20:59:48 CST 2020
     */
    int insert(UserStockTradeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_stock_trade_log
     *
     * @mbg.generated Wed Mar 04 20:59:48 CST 2020
     */
    int insertSelective(UserStockTradeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_stock_trade_log
     *
     * @mbg.generated Wed Mar 04 20:59:48 CST 2020
     */
    List<UserStockTradeLog> selectByExample(UserStockTradeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_stock_trade_log
     *
     * @mbg.generated Wed Mar 04 20:59:48 CST 2020
     */
    UserStockTradeLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_stock_trade_log
     *
     * @mbg.generated Wed Mar 04 20:59:48 CST 2020
     */
    int updateByPrimaryKeySelective(UserStockTradeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_stock_trade_log
     *
     * @mbg.generated Wed Mar 04 20:59:48 CST 2020
     */
    int updateByPrimaryKey(UserStockTradeLog record);
}