package com.goodluck2u.gl2u.entity;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.ID
     *
     * @mbg.generated Sat Feb 29 16:20:21 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.USER_NAME
     *
     * @mbg.generated Sat Feb 29 16:20:21 CST 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.ALL_MONEY
     *
     * @mbg.generated Sat Feb 29 16:20:21 CST 2020
     */
    private Integer allMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.CREATED_TIME
     *
     * @mbg.generated Sat Feb 29 16:20:21 CST 2020
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.UPDATED_TIME
     *
     * @mbg.generated Sat Feb 29 16:20:21 CST 2020
     */
    private Date updatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sat Feb 29 16:20:21 CST 2020
     */
    public User(String id, String userName, Integer allMoney, Date createdTime, Date updatedTime) {
        this.id = id;
        this.userName = userName;
        this.allMoney = allMoney;
        this.createdTime = createdTime;
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sat Feb 29 16:20:21 CST 2020
     */
    public User() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.ID
     *
     * @return the value of users.ID
     *
     * @mbg.generated Sat Feb 29 16:20:21 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.ID
     *
     * @param id the value for users.ID
     *
     * @mbg.generated Sat Feb 29 16:20:21 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.USER_NAME
     *
     * @return the value of users.USER_NAME
     *
     * @mbg.generated Sat Feb 29 16:20:21 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.USER_NAME
     *
     * @param userName the value for users.USER_NAME
     *
     * @mbg.generated Sat Feb 29 16:20:21 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.ALL_MONEY
     *
     * @return the value of users.ALL_MONEY
     *
     * @mbg.generated Sat Feb 29 16:20:21 CST 2020
     */
    public Integer getAllMoney() {
        return allMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.ALL_MONEY
     *
     * @param allMoney the value for users.ALL_MONEY
     *
     * @mbg.generated Sat Feb 29 16:20:21 CST 2020
     */
    public void setAllMoney(Integer allMoney) {
        this.allMoney = allMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.CREATED_TIME
     *
     * @return the value of users.CREATED_TIME
     *
     * @mbg.generated Sat Feb 29 16:20:21 CST 2020
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.CREATED_TIME
     *
     * @param createdTime the value for users.CREATED_TIME
     *
     * @mbg.generated Sat Feb 29 16:20:21 CST 2020
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.UPDATED_TIME
     *
     * @return the value of users.UPDATED_TIME
     *
     * @mbg.generated Sat Feb 29 16:20:21 CST 2020
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.UPDATED_TIME
     *
     * @param updatedTime the value for users.UPDATED_TIME
     *
     * @mbg.generated Sat Feb 29 16:20:21 CST 2020
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
}