package com.goodluck2u.gl2u.entity;

import java.math.BigDecimal;
import java.util.Date;

public class UserStockTradeLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stock_trade_log.ID
     *
     * @mbg.generated Wed Mar 04 20:51:14 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stock_trade_log.USER_ID
     *
     * @mbg.generated Wed Mar 04 20:51:14 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stock_trade_log.STOCK_ID
     *
     * @mbg.generated Wed Mar 04 20:51:14 CST 2020
     */
    private String stockId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stock_trade_log.TRADE_NUM
     *
     * @mbg.generated Wed Mar 04 20:51:14 CST 2020
     */
    private Integer tradeNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stock_trade_log.TRADE_PRICE
     *
     * @mbg.generated Wed Mar 04 20:51:14 CST 2020
     */
    private BigDecimal tradePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_stock_trade_log.CREATED_TIME
     *
     * @mbg.generated Wed Mar 04 20:51:14 CST 2020
     */
    private Date createdTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_stock_trade_log
     *
     * @mbg.generated Wed Mar 04 20:51:14 CST 2020
     */
    public UserStockTradeLog(String id, String userId, String stockId, Integer tradeNum, BigDecimal tradePrice, Date createdTime) {
        this.id = id;
        this.userId = userId;
        this.stockId = stockId;
        this.tradeNum = tradeNum;
        this.tradePrice = tradePrice;
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_stock_trade_log
     *
     * @mbg.generated Wed Mar 04 20:51:14 CST 2020
     */
    public UserStockTradeLog() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_stock_trade_log.ID
     *
     * @return the value of user_stock_trade_log.ID
     *
     * @mbg.generated Wed Mar 04 20:51:14 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_stock_trade_log.ID
     *
     * @param id the value for user_stock_trade_log.ID
     *
     * @mbg.generated Wed Mar 04 20:51:14 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_stock_trade_log.USER_ID
     *
     * @return the value of user_stock_trade_log.USER_ID
     *
     * @mbg.generated Wed Mar 04 20:51:14 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_stock_trade_log.USER_ID
     *
     * @param userId the value for user_stock_trade_log.USER_ID
     *
     * @mbg.generated Wed Mar 04 20:51:14 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_stock_trade_log.STOCK_ID
     *
     * @return the value of user_stock_trade_log.STOCK_ID
     *
     * @mbg.generated Wed Mar 04 20:51:14 CST 2020
     */
    public String getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_stock_trade_log.STOCK_ID
     *
     * @param stockId the value for user_stock_trade_log.STOCK_ID
     *
     * @mbg.generated Wed Mar 04 20:51:14 CST 2020
     */
    public void setStockId(String stockId) {
        this.stockId = stockId == null ? null : stockId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_stock_trade_log.TRADE_NUM
     *
     * @return the value of user_stock_trade_log.TRADE_NUM
     *
     * @mbg.generated Wed Mar 04 20:51:14 CST 2020
     */
    public Integer getTradeNum() {
        return tradeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_stock_trade_log.TRADE_NUM
     *
     * @param tradeNum the value for user_stock_trade_log.TRADE_NUM
     *
     * @mbg.generated Wed Mar 04 20:51:14 CST 2020
     */
    public void setTradeNum(Integer tradeNum) {
        this.tradeNum = tradeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_stock_trade_log.TRADE_PRICE
     *
     * @return the value of user_stock_trade_log.TRADE_PRICE
     *
     * @mbg.generated Wed Mar 04 20:51:14 CST 2020
     */
    public BigDecimal getTradePrice() {
        return tradePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_stock_trade_log.TRADE_PRICE
     *
     * @param tradePrice the value for user_stock_trade_log.TRADE_PRICE
     *
     * @mbg.generated Wed Mar 04 20:51:14 CST 2020
     */
    public void setTradePrice(BigDecimal tradePrice) {
        this.tradePrice = tradePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_stock_trade_log.CREATED_TIME
     *
     * @return the value of user_stock_trade_log.CREATED_TIME
     *
     * @mbg.generated Wed Mar 04 20:51:14 CST 2020
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_stock_trade_log.CREATED_TIME
     *
     * @param createdTime the value for user_stock_trade_log.CREATED_TIME
     *
     * @mbg.generated Wed Mar 04 20:51:14 CST 2020
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
}